POST http://localhost:3000/api/user/create
Content-Type: application/json

{
    "password": "password",
    "username": "bro1"
}

###

POST http://localhost:3000/api/times/67b628d7c22cdf7238ba76aa
Content-Type: application/json

{
    "created_at": "2025-02-24 14:30:45",
    "duration": 2000,
    "user_id": "67b628d7c22cdf7238ba76aa"
}
###

POST http://localhost:3000/api/user/login
Content-Type: application/json

{
    "password": "password",
    "username": "bro"
}