POST http://localhost:3000/api/user/create
Content-Type: application/json

{
    "username": "uzumaki",
    "password": "password"
}

###

POST http://localhost:3000/api/timelog
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YjYyOGQ3YzIyY2RmNzIzOGJhNzZhYSIsInVzZXJuYW1lIjoiYnJvIiwiaWF0IjoxNzQwNDAzOTAwLCJleHAiOjE3NDE2MTM1MDB9.3qpHkuTRmgkhEB02JOxpnGH_MbP4aS5l6S1PDBHaYDM

{
    "created_at": "2025-03-03",
    "duration": 10000,
    "user_id": "67b628d7c22cdf7238ba76aa"
}
###

POST http://localhost:3000/api/user/login
Content-Type: application/json

{
    "password": "password",
    "username": "uzumaki"
}
###

POST http://localhost:3000/ping
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YjYyOGQ3YzIyY2RmNzIzOGJhNzZhYSIsInVzZXJuYW1lIjoiYnJvIiwiaWF0IjoxNzQwNDAzOTAwLCJleHAiOjE3NDE2MTM1MDB9.3qpHkuTRmgkhEB02JOxpnGH_MbP4aS5l6S1PDBHaYDM

###

GET http://localhost:3000/api/ranking/2025-02-26/67b628d7c22cdf7238ba76aa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YjYyOGQ3YzIyY2RmNzIzOGJhNzZhYSIsInVzZXJuYW1lIjoiYnJvIiwiaWF0IjoxNzQwNDAzOTAwLCJleHAiOjE3NDE2MTM1MDB9.3qpHkuTRmgkhEB02JOxpnGH_MbP4aS5l6S1PDBHaYDM
