name: Deploy to production
on:
    push:
        branches: [main] 
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Trigger Deployment
              run: curl -X GET ${{ secrets.RENDER_DEPLOY_HOOK }}