name: E2E Tests with Maestro on Android

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    e2e-tests:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Enable KVM group perms
              run: |
                  echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
                  sudo udevadm control --reload-rules
                  sudo udevadm trigger --name-match=kvm

            - name: Set Up JDK (Required for Android SDK)
              uses: actions/setup-java@v3
              with:
                  distribution: 'temurin'
                  java-version: '17'

            - name: Set Up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 18

            - name: Install Dependencies
              working-directory: timerFront
              run: npm install

            - name: Install Expo CLI
              working-directory: timerFront
              run: npm install -g expo-cli

            - name: Install Maestro CLI
              run: |
                  curl -fsSL "https://get.maestro.mobile.dev" | bash
                  echo "$HOME/.maestro/bin" >> $GITHUB_PATH

            - name: Cache Gradle Dependencies
              uses: actions/cache@v3
              with:
                  path: ~/.gradle/caches
                  key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/*.xml') }}
                  restore-keys: gradle-${{ runner.os }}

            - name: Set Up Android SDK
              uses: android-actions/setup-android@v3

            - name: Start Expo Server
              run: NODE_ENV=test npx expo start --dev-client --non-interactive &
              working-directory: timerFront

            - name: Start Android Emulator and run maestro e2e tests
              uses: reactivecircus/android-emulator-runner@v2
              with:
                  api-level: 30
                  target: google_apis
                  arch: x86_64
                  profile: pixel_4
                  disable-animations: true
                  script: |
                      adb devices
                      adb wait-for-device shell input keyevent 82 # Unlock screen
                      cd timerFront
                      npx maestro test maestro/

            - name: Verify Emulator is Running
              run: adb shell getprop sys.boot_completed
