name: Unit test flow
on:
    push:
        branches: [main]

jobs:
    frontend-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Setup repository
              uses: actions/checkout@v3

            - name: Install dependencies
              run: npm install
              working-directory: ./timerFront

            - name: Run unit-tests
              run: npm run test-ci
              working-directory: ./timerFront

    backend-tests:
      runs-on: ubuntu-latest
      env: 
        SALT_ROUNDS: ${{ secrets.SALT_ROUNDS }}
        TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
        SECRET: ${{ secrets.SECRET }}
        PORT: ${{ secrets.PORT }}
      steps:
          - name: Checkout repository
            uses: actions/checkout@v3

          - name: Install backend dependencies
            run: npm install
            working-directory: ./backEnd

          - name: Run backend unit tests
            run: npm run test
            working-directory: ./backEnd